# Site settings
author: Victoria Mowbray
title: My Coding Blog, Welcome!!!
header-img: img/home-bg.png
email: vicki29644@icloud.com
copyright_name: Victoria Mowbray
description: > # this means to ignore newlines until "baseurl:"
  Blog, Blog, Blog.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  vicki29644

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
